[package]
name = "zero_copy_serde"
version = "0.1.0"
edition = "2021"

[dependencies]
async-channel = "2.3.1"
monoio = { version = "0.2.4", features = ["async-cancel", "sync", "macros", "poll-io", "iouring"] }
rand = "0.8"
rkyv = { version = "0.8.9", features = ["aligned"]}
